version: "3.8"
services:
  tomcat-service:
    build: .
    container_name: tomcat_application
    restart: on-failure
    ports:
      - 8081:8080
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - WAIT_HOSTS=postgres:54320
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-service:54320/wallet_db
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=password

  postgres:
    container_name: "postgres"
    image: postgres:15-alpine
    restart: always
    ports:
      - "54320:54320"
    environment:
      POSTGRES_DB: wallet_db
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -p 54320 -d wallet_db -U sa" ]
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      -p 54320