spring:
  server:
    port:8080
  liquibase:
    enabled:true
    defaultSchemaName: wallet_service
    liquibaseSchemaName: wallet_liquibase
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54320/wallet_db
    username: sa
    password: password
