spring:
  db:
    driver-class-name: org.postgresql.Driver
    DATASOURCE_URL: jdbc:postgresql://localhost:54320/wallet_db
    POSTGRES_USER: sa
    POSTGRES_PASSWORD: password
  liquibase:
    defaultSchemaName: wallet_service
    liquibaseSchemaName: wallet_liquibase
  test:
    DATASOURCE_URL: jdbc:postgresql://localhost:54321/wallet_db
    POSTGRES_USER: sa
    POSTGRES_PASSWORD: password
