spring:
  server:
    port:8080
  liquibase:
    enabled: true
    default-schema: wallet_service
    liquibase-schema: wallet_liquibase
    change-log: classpath:/db/changelog/changelog.xml
    contexts: test
  datasource:
    containerPort: 5432
    localPort: 54321
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:${spring.datasource.localPort}/wallet_db
    username: sa
    password: password
